import images from '../components/imageLoader';

const officerData = [
    {
        position: 'President',
        name: 'Libby Hodge',
        image: [ images['officerphotos/President.jpeg'] ],
        hometown: 'Libertyville',
        homeState:'IL',
        funFact: 'I like green bananas!',
    },
    {
        position: 'Vice President',
        name: 'Ryken Thompson',
        image: [images['officerphotos/Vice_President.jpeg'] ],
        hometown: 'San Carlos',
        homeState:'CA',
        funFact: 'I used to race mountain bikes in high school.',
    },
    {
        position: 'Secretary',
        name: 'Kelsey McDonald',
        image: [ images['officerphotos/Secretary.jpeg'] ],
        hometown: 'Burlingame',
        homeState:'CA',
        funFact: 'I have an obsession with Espresso Gu.',
    },
    {
        position: 'Public Relations',
        name: 'Kayla Wrobel',
        image: [],
        hometown: 'Burbank',
        homeState:'CA',
        funFact: `I'm an all state basketball player from high school and community college.`,
    },
    {
        position: 'Treasurer',
        name: 'Euan Huston',
        image: [],
        hometown: 'Pleasanton',
        homeState:'CA',
        funFact: 'If I was named John, then I would be John Houston the Eighth!',
    },
    {
        position: 'Apparel',
        name: 'Ty Jacobson',
        image: [],
        hometown: 'Lompoc',
        homeState:'CA',
        funFact: 'I have campled around the U.S. twice (42 states)!',
    },
    {
        position: 'Alumni Relations',
        name: 'Dirks Wright',
        image: [],
        hometown: 'Bellingham',
        homeState:'WA',
        funFact: 'I once was ran over by a charlift when skiing.',
    },
    {
        position: 'Sponsorship Coordinator',
        name: 'Colter Purcell',
        image: [],
        hometown: 'Hamilton',
        homeState:'MT',
        funFact: 'I went to 9 diffferent schools from K-12th grade.',
    },
    {
        position: 'Event Coordinator',
        name: 'Talulla Miller-Ross',
        image: [],
        hometown: 'Berkeley',
        homeState:'CA',
        funFact: 'I can eat a super burrito in 8 bites.',
    },
    {
        position: 'MTS Race Director',
        name: 'Dennis Kurmann',
        image: [],
        hometown: 'Montain View',
        homeState:'CA',
        funFact: 'I eat a lot of peanut butter',
    },
    {
        position: 'TdD Race Director',
        name: 'Ian Schaub',
        image: [],
        hometown: 'Seattle',
        homeState:'WA',
        funFact: 'I can talk for over an hour straight about the current state of the Seattle Mariners.',
    },
    {
        position: 'Heart and Soles Race Director',
        name: 'Brenton Duzi',
        image: [],
        hometown: 'Fresno',
        homeState:'CA',
        funFact: 'I tape my mouth shut when I sleep.',
    },
    {
        position: 'Womens Coordinator',
        name: 'Cassandra Richardson',
        image: [],
        hometown: 'Napa',
        homeState:'CA',
        funFact: 'I love applesauce and I eat it almost everyday.',
    },
    {
        position: 'Pro Coach',
        name: 'Scott Machado',
        image: [],
        hometown: 'San Jose',
        homeState:'CA',
        funFact: 'I raced at 2007 Age Group World Triathlon Championships in Hamburg, Germany.',
    },
    {
        position: 'Student Head Coach',
        name: 'Finn Balfe',
        image: [],
        hometown: 'Highlands Ranch',
        homeState:'CO',
        funFact: 'Other than triathlon, I love to ski and surf!',
    },
    {
        position: 'Head Run Coach',
        name: 'Cody Balazs',
        image: [],
        hometown: 'San Diego',
        homeState:'CA',
        funFact: 'I am better surfing than swimming.',
    },
    {
        position: 'Head Swim Coach',
        name: 'Maxwell Casem',
        image: [],
        hometown: 'Long Beach',
        homeState:'CA',
        funFact: 'I have an unhealthy obsession over orange.',
    },
    {
        position: 'Head Bike Coach',
        name: 'Simon Phipps',
        image: [],
        hometown: 'Norwich',
        homeState:'VT',
        funFact: 'I am the first person at Cal Poly to ride a unicycle with clipless pedals.',
    },
]

export default officerData;